### ISSUE TITLE
报错无法启动

### ISSUE THREAD

**Issue by DMB-codegang** [NapNeko/NapCat-Docker#33]
docker容器启动以后就报错，webui也开不起来

日志：
usermod: invalid user ID '$(id'
groupmod: invalid group ID '$(id'
usermod: group '$(id' does not exist
chown: invalid option -- 'u'
Try 'chown --help' for more information.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[25:0903/230829.842203:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[25:0903/230830.095314:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[25:0903/230830.095391:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[25:0903/230830.097258:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[25:0903/230830.097364:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[25:0903/230830.097440:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[25:0903/230830.097460:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Failed to create /app/.cache for shader cache (Permission denied)---disabling.
[57:0903/230830.196274:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[57:0903/230830.196454:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[57:0903/230830.196632:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[57:0903/230830.196746:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[57:0903/230830.196856:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
[57:0903/230830.196938:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
[57:0903/230830.197026:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
[57:0903/230830.200518:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
Failed to create /app/.cache for shader cache (Permission denied)---disabling.
[85:0903/230830.320625:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[85:0903/230830.320788:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[85:0903/230830.320951:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[85:0903/230830.321029:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[85:0903/230830.321120:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
[85:0903/230830.321197:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
[85:0903/230830.321262:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
[85:0903/230830.322995:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
NapCat Shell App Loading...
(node:25) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/app/napcat/logs/2024-09-03_23-08-30.415.log'
    at Object.writeFileSync (node:fs:2346:20)
    at Object.appendFileSync (node:fs:2427:6)
    at RollingFileStream._renewWriteStream (/app/napcat/node_modules/streamroller/lib/RollingFileWriteStream.js:312:8)
    at new RollingFileWriteStream (/app/napcat/node_modules/streamroller/lib/RollingFileWriteStream.js:94:10)
    at new RollingFileStream (/app/napcat/node_modules/streamroller/lib/RollingFileStream.js:18:5)
    at openTheStream (/app/napcat/node_modules/log4js/lib/appenders/file.js:64:20)
    at fileAppender (/app/napcat/node_modules/log4js/lib/appenders/file.js:84:16)
    at Object.configure (/app/napcat/node_modules/log4js/lib/appenders/file.js:144:10)
    at /app/napcat/node_modules/log4js/lib/appenders/index.js:117:29
    at Object.onlyOnMaster (/app/napcat/node_modules/log4js/lib/clustering.js:87:50)
(Use `qq --trace-warnings ...` to show where the warning was created)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Failed to create /app/.cache for shader cache (Permission denied)---disabling.
[104:0903/230830.515636:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[104:0903/230830.515785:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[104:0903/230830.515974:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[104:0903/230830.516072:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[104:0903/230830.516183:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
[104:0903/230830.516257:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
[104:0903/230830.516376:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
[104:0903/230830.518236:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization

**Comment by MliKiowa** [comment]
替换 userid为0 groupid为0 你仔细看看文档

**Comment by MliKiowa** [comment]
你弄错了这个 导致无权限 如果不会可以使用一键脚本启动docker

**Comment by MliKiowa** [comment]
如果仍然有疑问 请前往Napcat Q群

**Comment by DMB-codegang** [comment]
感谢回复，我最后通过不挂载NapCat配置文件的文件夹解决了这个问题，主打一个能跑就行😁👍
