### ISSUE TITLE
发送消息时报错 [发生错误 Error: 缺少参数 group_id 或 user_id]

### ISSUE THREAD

**Issue by Natane0808** [NapNeko/NapCat-Docker#40]
# docker-compose文件

~~~ yml
# docker-compose.yml
version: "3"
services:
    napcat:
        environment:
            - ACCOUNT=xxxxxxxxx
            - WS_ENABLE=true
            - NAPCAT_GID=0
            - NAPCAT_UID=0
        ports:
            - 3001:3001
            - 6099:6099
        volumes:
            - /www/data/napcat/QQ:/app/.config/QQ
            - /www/data/napcat/config:/app/napcat/config
        container_name: napcat
        network_mode: xxxxxx
        restart: always
        image: mlikiowa/napcat-docker:latest
~~~
# 错误日志
~~~
2024-10-24 15:35:55 [ERROR] 机器人(xxxxxx) | 发生错误 Error: 缺少参数 group_id 或 user_id
    at GoCQHTTPMarkMsgAsRead.getPeer (file:///app/napcat/napcat.mjs:34612:13)
    at GoCQHTTPMarkMsgAsRead._handle (file:///app/napcat/napcat.mjs:34617:67)
    at GoCQHTTPMarkMsgAsRead.websocketHandle (file:///app/napcat/napcat.mjs:33628:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OB11PassiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:19688:21)
~~~

**Comment by MliKiowa** [comment]
这个接口不是标准实现 需要传入群号或者QQ号

**Comment by MliKiowa** [comment]
我说的是你调用GoCQHTTPMarkMsgAsRead这个接口时
